Add support for knocks
mautrix/python pull request #103
Opened 2022-05-27 07:43 UTC by maltee1

2022-06-02 08:08 UTC, tulir requested changes

2022-06-02 08:08 UTC, tulir commented on mautrix/bridge/matrix.py
> +                    )
This seems to be missing the sender and reason

2022-06-02 08:08 UTC, tulir commented on mautrix/bridge/matrix.py
> +                )
This one doesn't need the sender (reason might still make sense)

2022-06-02 08:08 UTC, tulir commented on mautrix/bridge/matrix.py
> +        pass
The parameters here don't match what they're called with

2022-06-08 07:36 UTC, maltee1 commented
merge?

2022-06-17 13:10 UTC, merged